#!/usr/bin/env python3
"""
Real-world transcription tests with reference outputs from JavaScript implementation.
Generated by generate_reference_transcriptions.py
"""

import pytest
from src.glaemscribe.parsers.mode_parser import ModeParser

REAL_WORLD_TEST_CASES = [
    {
        'mode': 'quenya-tengwar-classical',
        'input': 'Ai ! laurië lantar lassi súrinen ,',
        'expected': 'lE Á j.E7T`V jE4#6 jE,T 8~M7T5$5 =',
        'description': 'Quenya phrase - Namárië opening'
    },
    {
        'mode': 'quenya-tengwar-classical',
        'input': 'Elen síla lúmenn omentielvo',
        'expected': '`VjR5 8~BjE j~Mt$5" `Nt$4%`VjyY',
        'description': 'Quenya greeting - A star shines'
    },
    {
        'mode': 'quenya-tengwar-classical',
        'input': 'aiya',
        'expected': 'lEhÍE',
        'description': 'Simple Quenya word'
    },
]

def transcribe_mode(mode_name: str, text: str) -> str:
    """Helper function to transcribe text using a specific mode."""
    parser = ModeParser()
    mode_file = f"resources/glaemresources/modes/{mode_name}.glaem"
    mode = parser.parse(mode_file)
    mode.processor.finalize({})
    result = mode.transcribe(text)
    return result[1] if result[0] else result[1]

@pytest.mark.parametrize("test_case", REAL_WORLD_TEST_CASES)
def test_real_world_transcription(test_case):
    """Test real-world transcription examples against JS outputs."""
    result = transcribe_mode(test_case["mode"], test_case["input"])
    assert result == test_case["expected"], (
        f"Transcription mismatch for {test_case['input']}\n"
        f"Expected: {test_case['expected']}\n"
        f"Got:      {result}"
    )
